# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-08 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
