# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20171106_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='top',
            field=models.IntegerField(default=0, verbose_name='置顶'),
        ),
    ]
